<?php

namespace Smalot\Vagrant\DashboardBundle\Repository;

/**
 * ProcessOutputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessOutputRepository extends \Doctrine\ORM\EntityRepository
{
}
