fos_rest:
    param_fetcher_listener: true
    format_listener:
        rules:
            fallback_format: json
            prefer_extension: false
            priorities: [json]
    view:
        view_response_listener: force
        formats:
            json: true
            xml: false
            jsonp: false
            rss: false
            html: false
        failed_validation: HTTP_BAD_REQUEST
