smalot_vagrant_dashboard:
    resource: "@SmalotVagrantDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

smalot_vagrant_rest:
    resource: "@SmalotVagrantRestBundle/Controller/"
    type:     annotation
    prefix:   /api
